### ISSUE TITLE
Provável Projeto

### ISSUE THREAD

**Issue by Gguidini** [VerasUnB/TP1.Project#3]
_Provavelmente_ faremos um jogo rapazes.

É um projeto divertido e que é perfeito para treinar todos os conceitos de orientação à objeto. Além disso o Loff tem bastante experiência nessa área, então facilita as coisas.

Dito isso, neste issue vamos dar ideias de um **jogo concreto para ser feito**. Quanto mais cedo a gente decidir qual fazer, melhor será. Nenhum problema em se inspirar em coisas já existentes, mas ideias originais são mais interessantes.

Sugestões podem ser em 2 sentidos (preferencialmente ambos): Tipo de jogo e temática.

**Comment by vitordullens** [comment]
Mudança de planos
